source 'https://rubygems.org'

gem 'rails', '~> 5.0.2'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'

gem 'devise_token_auth'

group :development, :test do
  gem 'rubocop'
  gem 'pry-rails'
end

group :development do
  gem 'listen', '~> 3.0.5'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'rspec_api_documentation'
end

group :test do
  gem 'fuubar', require: false
  gem 'ffaker', require: false
  gem 'shoulda-matchers'
  gem 'database_cleaner', require: false
  gem 'factory_girl_rails', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
